---
closetlaptops:
  hosts:
    proxmox:
      ansible_user: root
      ansible_connection: ssh
      ansible_host: 192.168.1.100

    microk8s:
      ansible_user: jfmatth
      ansible_connection: ssh
      ansible_host: 192.168.1.101
      ansible_become: true

