---
- name: Setup
  hosts: closetlaptops

  tasks:
  - name: Close lid behavior
    ini_file:
      path: /etc/systemd/logind.conf
      section: Login
      option: HandleLidSwitch
      value: ignore
      backup: yes

    notify:
      - Restart logind


  handlers:
    - name: Restart logind
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: systemd-logind