---
- name: Setup
  hosts: laptops

  tasks:
  - name: Close lid behavior
    ini_file:
      path: /etc/systemd/logind.conf
      section: Login
      option: HandleLidSwitch
      value: ignore
      backup: yes

    notify:
      - Restart logind

  - name: Console off after 10s
    ansible.builtin.lineinfile:
      path: /etc/default/grub
      line: GRUB_CMDLINE_LINUX_DEFAULT="quiet consoleblank=10"
      create: yes

  handlers:
    - name: Restart logind
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: systemd-logind